queue_rules:
  - name: dependabot
    conditions:
      - author=dependabot[bot]
      - status-success=test
      - base=master

pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
    actions:
      queue:
        method: squash
        name: dependabot
