require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-md

AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - vendor/**/*

Performance/StringIdentifierArgument:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - html2rss.gemspec

RSpec/NestedGroups:
  Exclude:
    - spec/html2rss_spec.rb

RSpec/DescribeClass:
  Exclude:
    - spec/exe/**/*_spec.rb

RSpec/ExampleLength:
  Max: 7

RSpec/NamedSubject:
  Enabled: false

Style/AsciiComments:
  AllowedChars:
    - €

Style/FormatStringToken:
  Exclude:
    - spec/html2rss/attribute_post_processors/template_spec.rb
