plugins:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-md
  - rubocop-rake
  - rubocop-thread_safety

AllCops:
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - vendor/**/*

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"
    - html2rss.gemspec

Metrics/MethodLength:
  CountAsOne:
    - heredoc

RSpec/NestedGroups:
  Exclude:
    - spec/lib/html2rss_spec.rb

RSpec/DescribeClass:
  Exclude:
    - spec/exe/**/*_spec.rb
    - spec/examples/**/*_spec.rb

RSpec/NamedSubject:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: always

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Layout/ClassStructure:
  Enabled: true
