require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-md
  - rubocop-rake

AllCops:
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - vendor/**/*

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"
    - html2rss.gemspec

RSpec/NestedGroups:
  Exclude:
    - spec/lib/html2rss_spec.rb

RSpec/DescribeClass:
  Exclude:
    - spec/exe/**/*_spec.rb

RSpec/NamedSubject:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Layout/ClassStructure:
  Enabled: true
