name: release gem

on:
  release:
    types: [published]

concurrency:
  group: release-gem-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release_gem:
    name: Release gem to RubyGems.org
    runs-on: ubuntu-latest

    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
      contents: write

    steps:
      - uses: actions/checkout@v7

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ruby

      - name: Publish gem
        uses: rubygems/release-gem@v1
